// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcH2NE9zEOhA2WD7z_TNfr0WVmRogLCeI',
    appId: '1:552086645656:web:b20630387fbee4c2c499ed',
    messagingSenderId: '552086645656',
    projectId: 'workout-app-e94be',
    authDomain: 'workout-app-e94be.firebaseapp.com',
    storageBucket: 'workout-app-e94be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnbaBR8TTVxc638WSQorBDMD10GoOMuGA',
    appId: '1:552086645656:android:03f14007d393a1f7c499ed',
    messagingSenderId: '552086645656',
    projectId: 'workout-app-e94be',
    storageBucket: 'workout-app-e94be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAquKzoHUgy37ioFOuYFxHhVE59ysSN9sY',
    appId: '1:552086645656:ios:dcb9d08c0eb53eb6c499ed',
    messagingSenderId: '552086645656',
    projectId: 'workout-app-e94be',
    storageBucket: 'workout-app-e94be.appspot.com',
    iosClientId: '552086645656-0ed0pdve9c8eollhv7n4saj368v74m18.apps.googleusercontent.com',
    iosBundleId: 'io.github.discusser.workoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAquKzoHUgy37ioFOuYFxHhVE59ysSN9sY',
    appId: '1:552086645656:ios:65389a34c9ab0f7ec499ed',
    messagingSenderId: '552086645656',
    projectId: 'workout-app-e94be',
    storageBucket: 'workout-app-e94be.appspot.com',
    iosClientId: '552086645656-apqfahfn3o86oc67qumcangiqs9dkrfc.apps.googleusercontent.com',
    iosBundleId: 'io.github.discusser.workoutApp.RunnerTests',
  );
}
